// Code generated by pggen. DO NOT EDIT.

package author

import (
	"context"
	"fmt"
	"sync"

	pgxdecimal "github.com/jackc/pgx-shopspring-decimal"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type QueryName struct{}

// Querier is a typesafe Go interface backed by SQL queries.
type Querier interface {
	// FindAuthorById finds one (or zero) authors by ID.
	FindAuthorByID(ctx context.Context, authorID int32) (FindAuthorByIDRow, error)

	// FindAuthors finds authors by first name.
	FindAuthors(ctx context.Context, firstName string) ([]FindAuthorsRow, error)

	// FindAuthorNames finds one (or zero) authors by ID.
	FindAuthorNames(ctx context.Context, authorID int32) ([]FindAuthorNamesRow, error)

	// FindFirstNames finds one (or zero) authors by ID.
	FindFirstNames(ctx context.Context, authorID int32) ([]*string, error)

	// DeleteAuthors deletes authors with a first name of "joe".
	DeleteAuthors(ctx context.Context) (pgconn.CommandTag, error)

	// DeleteAuthorsByFirstName deletes authors by first name.
	DeleteAuthorsByFirstName(ctx context.Context, firstName string) (pgconn.CommandTag, error)

	// DeleteAuthorsByFullName deletes authors by the full name.
	DeleteAuthorsByFullName(ctx context.Context, params DeleteAuthorsByFullNameParams) (pgconn.CommandTag, error)

	// InsertAuthor inserts an author by name and returns the ID.
	InsertAuthor(ctx context.Context, firstName string, lastName string) (int32, error)

	// InsertAuthorSuffix inserts an author by name and suffix and returns the
	// entire row.
	InsertAuthorSuffix(ctx context.Context, params InsertAuthorSuffixParams) (InsertAuthorSuffixRow, error)

	StringAggFirstName(ctx context.Context, authorID int32) (*string, error)

	ArrayAggFirstName(ctx context.Context, authorID int32) ([]string, error)

	// FindAuthorById finds one (or zero) authors by ID.
	QueueFindAuthorByID(batch *pgx.Batch, authorID int32, onResult func(FindAuthorByIDRow) error, onError func(err error) error)

	// FindAuthors finds authors by first name.
	QueueFindAuthors(batch *pgx.Batch, firstName string, onResult func([]FindAuthorsRow) error, onError func(err error) error)

	// FindAuthorNames finds one (or zero) authors by ID.
	QueueFindAuthorNames(batch *pgx.Batch, authorID int32, onResult func([]FindAuthorNamesRow) error, onError func(err error) error)

	// FindFirstNames finds one (or zero) authors by ID.
	QueueFindFirstNames(batch *pgx.Batch, authorID int32, onResult func([]*string) error, onError func(err error) error)

	// DeleteAuthors deletes authors with a first name of "joe".
	QueueDeleteAuthors(batch *pgx.Batch, onResult func(pgconn.CommandTag) error, onError func(err error) error)

	// DeleteAuthorsByFirstName deletes authors by first name.
	QueueDeleteAuthorsByFirstName(batch *pgx.Batch, firstName string, onResult func(pgconn.CommandTag) error, onError func(err error) error)

	// DeleteAuthorsByFullName deletes authors by the full name.
	QueueDeleteAuthorsByFullName(batch *pgx.Batch, params DeleteAuthorsByFullNameParams, onResult func(pgconn.CommandTag) error, onError func(err error) error)

	// InsertAuthor inserts an author by name and returns the ID.
	QueueInsertAuthor(batch *pgx.Batch, firstName string, lastName string, onResult func(int32) error, onError func(err error) error)

	// InsertAuthorSuffix inserts an author by name and suffix and returns the
	// entire row.
	QueueInsertAuthorSuffix(batch *pgx.Batch, params InsertAuthorSuffixParams, onResult func(InsertAuthorSuffixRow) error, onError func(err error) error)

	QueueStringAggFirstName(batch *pgx.Batch, authorID int32, onResult func(*string) error, onError func(err error) error)

	QueueArrayAggFirstName(batch *pgx.Batch, authorID int32, onResult func([]string) error, onError func(err error) error)
}

var _ Querier = &DBQuerier{}

type DBQuerier struct {
	conn    genericConn
	errWrap func(err error) error
}

// genericConn is a connection like *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
type genericConn interface {
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
	TypeMap() *pgtype.Map
	LoadType(ctx context.Context, typeName string) (*pgtype.Type, error)
}

// NewQuerier creates a DBQuerier
func NewQuerier(conn genericConn) *DBQuerier {
	return &DBQuerier{
		conn: conn,
		errWrap: func(err error) error {
			return err
		},
	}
}

var registerOnce sync.Once
var registerErr error

func registerTypes(ctx context.Context, conn genericConn) error {
	registerOnce.Do(func() {
		typeMap := conn.TypeMap()

		pgxdecimal.Register(typeMap)
		for _, typ := range typesToRegister {
			dt, err := conn.LoadType(ctx, typ)
			if err != nil {
				registerErr = fmt.Errorf("could not register type %q: %w", typ, err)
				return
			}
			typeMap.RegisterType(dt)
		}
	})

	return registerErr
}

var typesToRegister = []string{}

func addTypeToRegister(typ string) struct{} {
	typesToRegister = append(typesToRegister, typ)
	return struct{}{}
}

const findAuthorByIDSQL = `SELECT * FROM author WHERE author_id = $1;`

type FindAuthorByIDRow struct {
	AuthorID  int32   `json:"author_id"`
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Suffix    *string `json:"suffix"`
}

// FindAuthorByID implements Querier.FindAuthorByID.
func (q *DBQuerier) FindAuthorByID(ctx context.Context, authorID int32) (FindAuthorByIDRow, error) {
	ctx = context.WithValue(ctx, QueryName{}, "FindAuthorByID")

	err := registerTypes(ctx, q.conn)
	if err != nil {
		return FindAuthorByIDRow{}, q.errWrap(err)
	}
	rows, err := q.conn.Query(ctx, findAuthorByIDSQL, authorID)
	if err != nil {
		return FindAuthorByIDRow{}, fmt.Errorf("query FindAuthorByID: %w", q.errWrap(err))
	}
	res, err := pgx.CollectExactlyOneRow(rows, pgx.RowToStructByName[FindAuthorByIDRow])
	return res, q.errWrap(err)
}

// FindAuthorByID implements Batcher.FindAuthorByID.
func (q *DBQuerier) QueueFindAuthorByID(batch *pgx.Batch, authorID int32, onResult func(FindAuthorByIDRow) error, onError func(err error) error) {
	err := registerTypes(context.Background(), q.conn)
	if err != nil {
		panic(q.errWrap(fmt.Errorf("could not register types: %w", err)))
	}

	queuedQuery := batch.Queue(findAuthorByIDSQL, authorID)
	queuedQuery.Fn = func(br pgx.BatchResults) error {
		rows, err := br.Query()
		if err != nil {
			if onError != nil {
				return q.errWrap(onError(err))
			}
			return q.errWrap(err)
		}
		res, err := pgx.CollectExactlyOneRow(rows, pgx.RowToStructByName[FindAuthorByIDRow])
		if err != nil {
			if onError != nil {
				return q.errWrap(onError(err))
			}
			return q.errWrap(err)
		}

		if onResult == nil {
			return nil
		}

		return q.errWrap(onResult(res))
	}
}

const findAuthorsSQL = `SELECT * FROM author WHERE first_name = $1;`

type FindAuthorsRow struct {
	AuthorID  int32   `json:"author_id"`
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Suffix    *string `json:"suffix"`
}

// FindAuthors implements Querier.FindAuthors.
func (q *DBQuerier) FindAuthors(ctx context.Context, firstName string) ([]FindAuthorsRow, error) {
	ctx = context.WithValue(ctx, QueryName{}, "FindAuthors")

	err := registerTypes(ctx, q.conn)
	if err != nil {
		return nil, q.errWrap(err)
	}
	rows, err := q.conn.Query(ctx, findAuthorsSQL, firstName)
	if err != nil {
		return nil, fmt.Errorf("query FindAuthors: %w", q.errWrap(err))
	}
	res, err := pgx.CollectRows(rows, pgx.RowToStructByName[FindAuthorsRow])
	return res, q.errWrap(err)
}

// FindAuthors implements Batcher.FindAuthors.
func (q *DBQuerier) QueueFindAuthors(batch *pgx.Batch, firstName string, onResult func([]FindAuthorsRow) error, onError func(err error) error) {
	err := registerTypes(context.Background(), q.conn)
	if err != nil {
		panic(q.errWrap(fmt.Errorf("could not register types: %w", err)))
	}

	queuedQuery := batch.Queue(findAuthorsSQL, firstName)
	queuedQuery.Fn = func(br pgx.BatchResults) error {
		rows, err := br.Query()
		if err != nil {
			if onError != nil {
				return q.errWrap(onError(err))
			}
			return q.errWrap(err)
		}
		res, err := pgx.CollectRows(rows, pgx.RowToStructByName[FindAuthorsRow])
		if err != nil {
			if onError != nil {
				return q.errWrap(onError(err))
			}
			return q.errWrap(err)
		}

		if onResult == nil {
			return nil
		}

		return q.errWrap(onResult(res))
	}
}

const findAuthorNamesSQL = `SELECT first_name, last_name FROM author ORDER BY author_id = $1;`

type FindAuthorNamesRow struct {
	FirstName *string `json:"first_name"`
	LastName  *string `json:"last_name"`
}

// FindAuthorNames implements Querier.FindAuthorNames.
func (q *DBQuerier) FindAuthorNames(ctx context.Context, authorID int32) ([]FindAuthorNamesRow, error) {
	ctx = context.WithValue(ctx, QueryName{}, "FindAuthorNames")

	err := registerTypes(ctx, q.conn)
	if err != nil {
		return nil, q.errWrap(err)
	}
	rows, err := q.conn.Query(ctx, findAuthorNamesSQL, authorID)
	if err != nil {
		return nil, fmt.Errorf("query FindAuthorNames: %w", q.errWrap(err))
	}
	res, err := pgx.CollectRows(rows, pgx.RowToStructByName[FindAuthorNamesRow])
	return res, q.errWrap(err)
}

// FindAuthorNames implements Batcher.FindAuthorNames.
func (q *DBQuerier) QueueFindAuthorNames(batch *pgx.Batch, authorID int32, onResult func([]FindAuthorNamesRow) error, onError func(err error) error) {
	err := registerTypes(context.Background(), q.conn)
	if err != nil {
		panic(q.errWrap(fmt.Errorf("could not register types: %w", err)))
	}

	queuedQuery := batch.Queue(findAuthorNamesSQL, authorID)
	queuedQuery.Fn = func(br pgx.BatchResults) error {
		rows, err := br.Query()
		if err != nil {
			if onError != nil {
				return q.errWrap(onError(err))
			}
			return q.errWrap(err)
		}
		res, err := pgx.CollectRows(rows, pgx.RowToStructByName[FindAuthorNamesRow])
		if err != nil {
			if onError != nil {
				return q.errWrap(onError(err))
			}
			return q.errWrap(err)
		}

		if onResult == nil {
			return nil
		}

		return q.errWrap(onResult(res))
	}
}

const findFirstNamesSQL = `SELECT first_name FROM author ORDER BY author_id = $1;`

// FindFirstNames implements Querier.FindFirstNames.
func (q *DBQuerier) FindFirstNames(ctx context.Context, authorID int32) ([]*string, error) {
	ctx = context.WithValue(ctx, QueryName{}, "FindFirstNames")

	err := registerTypes(ctx, q.conn)
	if err != nil {
		return nil, q.errWrap(err)
	}
	rows, err := q.conn.Query(ctx, findFirstNamesSQL, authorID)
	if err != nil {
		return nil, fmt.Errorf("query FindFirstNames: %w", q.errWrap(err))
	}
	res, err := pgx.CollectRows(rows, pgx.RowTo[*string])
	return res, q.errWrap(err)
}

// FindFirstNames implements Batcher.FindFirstNames.
func (q *DBQuerier) QueueFindFirstNames(batch *pgx.Batch, authorID int32, onResult func([]*string) error, onError func(err error) error) {
	err := registerTypes(context.Background(), q.conn)
	if err != nil {
		panic(q.errWrap(fmt.Errorf("could not register types: %w", err)))
	}

	queuedQuery := batch.Queue(findFirstNamesSQL, authorID)
	queuedQuery.Fn = func(br pgx.BatchResults) error {
		rows, err := br.Query()
		if err != nil {
			if onError != nil {
				return q.errWrap(onError(err))
			}
			return q.errWrap(err)
		}
		res, err := pgx.CollectRows(rows, pgx.RowTo[*string])
		if err != nil {
			if onError != nil {
				return q.errWrap(onError(err))
			}
			return q.errWrap(err)
		}

		if onResult == nil {
			return nil
		}

		return q.errWrap(onResult(res))
	}
}

const deleteAuthorsSQL = `DELETE FROM author WHERE first_name = 'joe';`

// DeleteAuthors implements Querier.DeleteAuthors.
func (q *DBQuerier) DeleteAuthors(ctx context.Context) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, QueryName{}, "DeleteAuthors")

	err := registerTypes(ctx, q.conn)
	if err != nil {
		return pgconn.CommandTag{}, q.errWrap(err)
	}
	cmdTag, err := q.conn.Exec(ctx, deleteAuthorsSQL)
	if err != nil {
		return pgconn.CommandTag{}, fmt.Errorf("exec query DeleteAuthors: %w", q.errWrap(err))
	}
	return cmdTag, q.errWrap(err)
}

// DeleteAuthors implements Batcher.DeleteAuthors.
func (q *DBQuerier) QueueDeleteAuthors(batch *pgx.Batch, onResult func(pgconn.CommandTag) error, onError func(err error) error) {
	err := registerTypes(context.Background(), q.conn)
	if err != nil {
		panic(q.errWrap(fmt.Errorf("could not register types: %w", err)))
	}

	queuedQuery := batch.Queue(deleteAuthorsSQL)
	queuedQuery.Fn = func(br pgx.BatchResults) error {
		tag, err := br.Exec()
		if err != nil {
			if onError != nil {
				return q.errWrap(onError(err))
			}
			return q.errWrap(err)
		}

		if onResult == nil {
			return nil
		}

		return q.errWrap(onResult(tag))
	}
}

const deleteAuthorsByFirstNameSQL = `DELETE FROM author WHERE first_name = $1;`

// DeleteAuthorsByFirstName implements Querier.DeleteAuthorsByFirstName.
func (q *DBQuerier) DeleteAuthorsByFirstName(ctx context.Context, firstName string) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, QueryName{}, "DeleteAuthorsByFirstName")

	err := registerTypes(ctx, q.conn)
	if err != nil {
		return pgconn.CommandTag{}, q.errWrap(err)
	}
	cmdTag, err := q.conn.Exec(ctx, deleteAuthorsByFirstNameSQL, firstName)
	if err != nil {
		return pgconn.CommandTag{}, fmt.Errorf("exec query DeleteAuthorsByFirstName: %w", q.errWrap(err))
	}
	return cmdTag, q.errWrap(err)
}

// DeleteAuthorsByFirstName implements Batcher.DeleteAuthorsByFirstName.
func (q *DBQuerier) QueueDeleteAuthorsByFirstName(batch *pgx.Batch, firstName string, onResult func(pgconn.CommandTag) error, onError func(err error) error) {
	err := registerTypes(context.Background(), q.conn)
	if err != nil {
		panic(q.errWrap(fmt.Errorf("could not register types: %w", err)))
	}

	queuedQuery := batch.Queue(deleteAuthorsByFirstNameSQL, firstName)
	queuedQuery.Fn = func(br pgx.BatchResults) error {
		tag, err := br.Exec()
		if err != nil {
			if onError != nil {
				return q.errWrap(onError(err))
			}
			return q.errWrap(err)
		}

		if onResult == nil {
			return nil
		}

		return q.errWrap(onResult(tag))
	}
}

const deleteAuthorsByFullNameSQL = `DELETE
FROM author
WHERE first_name = $1
  AND last_name = $2
  AND suffix = $3;`

type DeleteAuthorsByFullNameParams struct {
	FirstName string `json:"FirstName"`
	LastName  string `json:"LastName"`
	Suffix    string `json:"Suffix"`
}

// DeleteAuthorsByFullName implements Querier.DeleteAuthorsByFullName.
func (q *DBQuerier) DeleteAuthorsByFullName(ctx context.Context, params DeleteAuthorsByFullNameParams) (pgconn.CommandTag, error) {
	ctx = context.WithValue(ctx, QueryName{}, "DeleteAuthorsByFullName")

	err := registerTypes(ctx, q.conn)
	if err != nil {
		return pgconn.CommandTag{}, q.errWrap(err)
	}
	cmdTag, err := q.conn.Exec(ctx, deleteAuthorsByFullNameSQL, params.FirstName, params.LastName, params.Suffix)
	if err != nil {
		return pgconn.CommandTag{}, fmt.Errorf("exec query DeleteAuthorsByFullName: %w", q.errWrap(err))
	}
	return cmdTag, q.errWrap(err)
}

// DeleteAuthorsByFullName implements Batcher.DeleteAuthorsByFullName.
func (q *DBQuerier) QueueDeleteAuthorsByFullName(batch *pgx.Batch, params DeleteAuthorsByFullNameParams, onResult func(pgconn.CommandTag) error, onError func(err error) error) {
	err := registerTypes(context.Background(), q.conn)
	if err != nil {
		panic(q.errWrap(fmt.Errorf("could not register types: %w", err)))
	}

	queuedQuery := batch.Queue(deleteAuthorsByFullNameSQL, params.FirstName, params.LastName, params.Suffix)
	queuedQuery.Fn = func(br pgx.BatchResults) error {
		tag, err := br.Exec()
		if err != nil {
			if onError != nil {
				return q.errWrap(onError(err))
			}
			return q.errWrap(err)
		}

		if onResult == nil {
			return nil
		}

		return q.errWrap(onResult(tag))
	}
}

const insertAuthorSQL = `INSERT INTO author (first_name, last_name)
VALUES ($1, $2)
RETURNING author_id;`

// InsertAuthor implements Querier.InsertAuthor.
func (q *DBQuerier) InsertAuthor(ctx context.Context, firstName string, lastName string) (int32, error) {
	ctx = context.WithValue(ctx, QueryName{}, "InsertAuthor")

	err := registerTypes(ctx, q.conn)
	if err != nil {
		return 0, q.errWrap(err)
	}
	rows, err := q.conn.Query(ctx, insertAuthorSQL, firstName, lastName)
	if err != nil {
		return 0, fmt.Errorf("query InsertAuthor: %w", q.errWrap(err))
	}
	res, err := pgx.CollectExactlyOneRow(rows, pgx.RowTo[int32])
	return res, q.errWrap(err)
}

// InsertAuthor implements Batcher.InsertAuthor.
func (q *DBQuerier) QueueInsertAuthor(batch *pgx.Batch, firstName string, lastName string, onResult func(int32) error, onError func(err error) error) {
	err := registerTypes(context.Background(), q.conn)
	if err != nil {
		panic(q.errWrap(fmt.Errorf("could not register types: %w", err)))
	}

	queuedQuery := batch.Queue(insertAuthorSQL, firstName, lastName)
	queuedQuery.Fn = func(br pgx.BatchResults) error {
		rows, err := br.Query()
		if err != nil {
			if onError != nil {
				return q.errWrap(onError(err))
			}
			return q.errWrap(err)
		}
		res, err := pgx.CollectExactlyOneRow(rows, pgx.RowTo[int32])
		if err != nil {
			if onError != nil {
				return q.errWrap(onError(err))
			}
			return q.errWrap(err)
		}

		if onResult == nil {
			return nil
		}

		return q.errWrap(onResult(res))
	}
}

const insertAuthorSuffixSQL = `INSERT INTO author (first_name, last_name, suffix)
VALUES ($1, $2, $3)
RETURNING author_id, first_name, last_name, suffix;`

type InsertAuthorSuffixParams struct {
	FirstName string `json:"FirstName"`
	LastName  string `json:"LastName"`
	Suffix    string `json:"Suffix"`
}

type InsertAuthorSuffixRow struct {
	AuthorID  int32   `json:"author_id"`
	FirstName string  `json:"first_name"`
	LastName  string  `json:"last_name"`
	Suffix    *string `json:"suffix"`
}

// InsertAuthorSuffix implements Querier.InsertAuthorSuffix.
func (q *DBQuerier) InsertAuthorSuffix(ctx context.Context, params InsertAuthorSuffixParams) (InsertAuthorSuffixRow, error) {
	ctx = context.WithValue(ctx, QueryName{}, "InsertAuthorSuffix")

	err := registerTypes(ctx, q.conn)
	if err != nil {
		return InsertAuthorSuffixRow{}, q.errWrap(err)
	}
	rows, err := q.conn.Query(ctx, insertAuthorSuffixSQL, params.FirstName, params.LastName, params.Suffix)
	if err != nil {
		return InsertAuthorSuffixRow{}, fmt.Errorf("query InsertAuthorSuffix: %w", q.errWrap(err))
	}
	res, err := pgx.CollectExactlyOneRow(rows, pgx.RowToStructByName[InsertAuthorSuffixRow])
	return res, q.errWrap(err)
}

// InsertAuthorSuffix implements Batcher.InsertAuthorSuffix.
func (q *DBQuerier) QueueInsertAuthorSuffix(batch *pgx.Batch, params InsertAuthorSuffixParams, onResult func(InsertAuthorSuffixRow) error, onError func(err error) error) {
	err := registerTypes(context.Background(), q.conn)
	if err != nil {
		panic(q.errWrap(fmt.Errorf("could not register types: %w", err)))
	}

	queuedQuery := batch.Queue(insertAuthorSuffixSQL, params.FirstName, params.LastName, params.Suffix)
	queuedQuery.Fn = func(br pgx.BatchResults) error {
		rows, err := br.Query()
		if err != nil {
			if onError != nil {
				return q.errWrap(onError(err))
			}
			return q.errWrap(err)
		}
		res, err := pgx.CollectExactlyOneRow(rows, pgx.RowToStructByName[InsertAuthorSuffixRow])
		if err != nil {
			if onError != nil {
				return q.errWrap(onError(err))
			}
			return q.errWrap(err)
		}

		if onResult == nil {
			return nil
		}

		return q.errWrap(onResult(res))
	}
}

const stringAggFirstNameSQL = `SELECT string_agg(first_name, ',') AS names FROM author WHERE author_id = $1;`

// StringAggFirstName implements Querier.StringAggFirstName.
func (q *DBQuerier) StringAggFirstName(ctx context.Context, authorID int32) (*string, error) {
	ctx = context.WithValue(ctx, QueryName{}, "StringAggFirstName")

	err := registerTypes(ctx, q.conn)
	if err != nil {
		return nil, q.errWrap(err)
	}
	rows, err := q.conn.Query(ctx, stringAggFirstNameSQL, authorID)
	if err != nil {
		return nil, fmt.Errorf("query StringAggFirstName: %w", q.errWrap(err))
	}
	res, err := pgx.CollectExactlyOneRow(rows, pgx.RowTo[*string])
	return res, q.errWrap(err)
}

// StringAggFirstName implements Batcher.StringAggFirstName.
func (q *DBQuerier) QueueStringAggFirstName(batch *pgx.Batch, authorID int32, onResult func(*string) error, onError func(err error) error) {
	err := registerTypes(context.Background(), q.conn)
	if err != nil {
		panic(q.errWrap(fmt.Errorf("could not register types: %w", err)))
	}

	queuedQuery := batch.Queue(stringAggFirstNameSQL, authorID)
	queuedQuery.Fn = func(br pgx.BatchResults) error {
		rows, err := br.Query()
		if err != nil {
			if onError != nil {
				return q.errWrap(onError(err))
			}
			return q.errWrap(err)
		}
		res, err := pgx.CollectExactlyOneRow(rows, pgx.RowTo[*string])
		if err != nil {
			if onError != nil {
				return q.errWrap(onError(err))
			}
			return q.errWrap(err)
		}

		if onResult == nil {
			return nil
		}

		return q.errWrap(onResult(res))
	}
}

const arrayAggFirstNameSQL = `SELECT array_agg(first_name) AS names FROM author WHERE author_id = $1;`

// ArrayAggFirstName implements Querier.ArrayAggFirstName.
func (q *DBQuerier) ArrayAggFirstName(ctx context.Context, authorID int32) ([]string, error) {
	ctx = context.WithValue(ctx, QueryName{}, "ArrayAggFirstName")

	err := registerTypes(ctx, q.conn)
	if err != nil {
		return nil, q.errWrap(err)
	}
	rows, err := q.conn.Query(ctx, arrayAggFirstNameSQL, authorID)
	if err != nil {
		return nil, fmt.Errorf("query ArrayAggFirstName: %w", q.errWrap(err))
	}
	res, err := pgx.CollectExactlyOneRow(rows, pgx.RowTo[[]string])
	return res, q.errWrap(err)
}

// ArrayAggFirstName implements Batcher.ArrayAggFirstName.
func (q *DBQuerier) QueueArrayAggFirstName(batch *pgx.Batch, authorID int32, onResult func([]string) error, onError func(err error) error) {
	err := registerTypes(context.Background(), q.conn)
	if err != nil {
		panic(q.errWrap(fmt.Errorf("could not register types: %w", err)))
	}

	queuedQuery := batch.Queue(arrayAggFirstNameSQL, authorID)
	queuedQuery.Fn = func(br pgx.BatchResults) error {
		rows, err := br.Query()
		if err != nil {
			if onError != nil {
				return q.errWrap(onError(err))
			}
			return q.errWrap(err)
		}
		res, err := pgx.CollectExactlyOneRow(rows, pgx.RowTo[[]string])
		if err != nil {
			if onError != nil {
				return q.errWrap(onError(err))
			}
			return q.errWrap(err)
		}

		if onResult == nil {
			return nil
		}

		return q.errWrap(onResult(res))
	}
}
