// Code generated by pggen. DO NOT EDIT.

package custom_types

import (
	"context"
	"fmt"
	"sync"

	pgxdecimal "github.com/jackc/pgx-shopspring-decimal"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/mypricehealth/pggen/example/custom_types/mytype"
)

type QueryName struct{}

// Querier is a typesafe Go interface backed by SQL queries.
type Querier interface {
	CustomTypes(ctx context.Context) (CustomTypesRow, error)

	CustomMyInt(ctx context.Context) (int, error)

	IntArray(ctx context.Context) ([][]int32, error)

	QueueCustomTypes(batch *pgx.Batch) *QueuedCustomTypes

	QueueCustomMyInt(batch *pgx.Batch) *QueuedCustomMyInt

	QueueIntArray(batch *pgx.Batch) *QueuedIntArray
}

var _ Querier = &DBQuerier{}

type DBQuerier struct {
	conn    genericConn
	errWrap func(err error) error
}

// genericConn is a connection like *pgx.Conn, pgx.Tx, or *pgxpool.Pool.
type genericConn interface {
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error)
	TypeMap() *pgtype.Map
	LoadType(ctx context.Context, typeName string) (*pgtype.Type, error)
}

// NewQuerier creates a DBQuerier
func NewQuerier(conn genericConn) *DBQuerier {
	return &DBQuerier{
		conn: conn,
		errWrap: func(err error) error {
			return err
		},
	}
}

var registerOnce sync.Once
var registerErr error

func registerTypes(ctx context.Context, conn genericConn) error {
	registerOnce.Do(func() {
		typeMap := conn.TypeMap()

		pgxdecimal.Register(typeMap)
		for _, typ := range typesToRegister {
			dt, err := conn.LoadType(ctx, typ)
			if err != nil {
				registerErr = fmt.Errorf("could not register type %q: %w", typ, err)
				return
			}
			typeMap.RegisterType(dt)
		}
	})

	return registerErr
}

var typesToRegister = []string{}

func addTypeToRegister(typ string) struct{} {
	typesToRegister = append(typesToRegister, typ)
	return struct{}{}
}

const customTypesSQL = `SELECT 'some_text', 1::bigint;`

type CustomTypesRow struct {
	Column mytype.String `json:"?column?"`
	Int8   CustomInt     `json:"int8"`
}

// CustomTypes implements Querier.CustomTypes.
func (q *DBQuerier) CustomTypes(ctx context.Context) (CustomTypesRow, error) {
	ctx = context.WithValue(ctx, QueryName{}, "CustomTypes")

	err := registerTypes(ctx, q.conn)
	if err != nil {
		return CustomTypesRow{}, q.errWrap(err)
	}
	rows, err := q.conn.Query(ctx, customTypesSQL)
	if err != nil {
		return CustomTypesRow{}, fmt.Errorf("query CustomTypes: %w", q.errWrap(err))
	}
	res, err := pgx.CollectExactlyOneRow(rows, pgx.RowToStructByName[CustomTypesRow])
	return res, q.errWrap(err)
}

type QueuedCustomTypes struct {
	wrapError func(err error) error
	onResult  func(CustomTypesRow) error
}

func (q *QueuedCustomTypes) WrapError(wrapError func(err error) error) {
	q.wrapError = wrapError
}

func (q *QueuedCustomTypes) OnResult(onResult func(CustomTypesRow) error) {
	q.onResult = onResult
}

func (q *QueuedCustomTypes) runWrapError(err error) error {
	if q.wrapError == nil {
		return err
	}

	return q.wrapError(err)
}

func (q *QueuedCustomTypes) runOnResult(result CustomTypesRow) error {
	if q.onResult == nil {
		return nil
	}

	return q.onResult(result)
}

// CustomTypes implements Batcher.CustomTypes.
func (q *DBQuerier) QueueCustomTypes(batch *pgx.Batch) *QueuedCustomTypes {
	err := registerTypes(context.Background(), q.conn)
	if err != nil {
		panic(q.errWrap(fmt.Errorf("could not register types: %w", err)))
	}

	queued := &QueuedCustomTypes{}

	queuedQuery := batch.Queue(customTypesSQL)
	queuedQuery.Fn = func(br pgx.BatchResults) error {
		rows, err := br.Query()
		if err != nil {
			return queued.runWrapError(err)
		}
		res, err := pgx.CollectExactlyOneRow(rows, pgx.RowToStructByName[CustomTypesRow])
		if err != nil {
			return queued.runWrapError(err)
		}

		return queued.runOnResult(res)
	}

	return queued
}

const customMyIntSQL = `SELECT '5'::my_int as int5;`

// CustomMyInt implements Querier.CustomMyInt.
func (q *DBQuerier) CustomMyInt(ctx context.Context) (int, error) {
	ctx = context.WithValue(ctx, QueryName{}, "CustomMyInt")

	err := registerTypes(ctx, q.conn)
	if err != nil {
		return 0, q.errWrap(err)
	}
	rows, err := q.conn.Query(ctx, customMyIntSQL)
	if err != nil {
		return 0, fmt.Errorf("query CustomMyInt: %w", q.errWrap(err))
	}
	res, err := pgx.CollectExactlyOneRow(rows, pgx.RowTo[int])
	return res, q.errWrap(err)
}

type QueuedCustomMyInt struct {
	wrapError func(err error) error
	onResult  func(int) error
}

func (q *QueuedCustomMyInt) WrapError(wrapError func(err error) error) {
	q.wrapError = wrapError
}

func (q *QueuedCustomMyInt) OnResult(onResult func(int) error) {
	q.onResult = onResult
}

func (q *QueuedCustomMyInt) runWrapError(err error) error {
	if q.wrapError == nil {
		return err
	}

	return q.wrapError(err)
}

func (q *QueuedCustomMyInt) runOnResult(result int) error {
	if q.onResult == nil {
		return nil
	}

	return q.onResult(result)
}

// CustomMyInt implements Batcher.CustomMyInt.
func (q *DBQuerier) QueueCustomMyInt(batch *pgx.Batch) *QueuedCustomMyInt {
	err := registerTypes(context.Background(), q.conn)
	if err != nil {
		panic(q.errWrap(fmt.Errorf("could not register types: %w", err)))
	}

	queued := &QueuedCustomMyInt{}

	queuedQuery := batch.Queue(customMyIntSQL)
	queuedQuery.Fn = func(br pgx.BatchResults) error {
		rows, err := br.Query()
		if err != nil {
			return queued.runWrapError(err)
		}
		res, err := pgx.CollectExactlyOneRow(rows, pgx.RowTo[int])
		if err != nil {
			return queued.runWrapError(err)
		}

		return queued.runOnResult(res)
	}

	return queued
}

const intArraySQL = `SELECT ARRAY ['5', '6', '7']::int[] as ints;`

// IntArray implements Querier.IntArray.
func (q *DBQuerier) IntArray(ctx context.Context) ([][]int32, error) {
	ctx = context.WithValue(ctx, QueryName{}, "IntArray")

	err := registerTypes(ctx, q.conn)
	if err != nil {
		return nil, q.errWrap(err)
	}
	rows, err := q.conn.Query(ctx, intArraySQL)
	if err != nil {
		return nil, fmt.Errorf("query IntArray: %w", q.errWrap(err))
	}
	res, err := pgx.CollectRows(rows, pgx.RowTo[[]int32])
	return res, q.errWrap(err)
}

type QueuedIntArray struct {
	wrapError func(err error) error
	onResult  func([][]int32) error
}

func (q *QueuedIntArray) WrapError(wrapError func(err error) error) {
	q.wrapError = wrapError
}

func (q *QueuedIntArray) OnResult(onResult func([][]int32) error) {
	q.onResult = onResult
}

func (q *QueuedIntArray) runWrapError(err error) error {
	if q.wrapError == nil {
		return err
	}

	return q.wrapError(err)
}

func (q *QueuedIntArray) runOnResult(result [][]int32) error {
	if q.onResult == nil {
		return nil
	}

	return q.onResult(result)
}

// IntArray implements Batcher.IntArray.
func (q *DBQuerier) QueueIntArray(batch *pgx.Batch) *QueuedIntArray {
	err := registerTypes(context.Background(), q.conn)
	if err != nil {
		panic(q.errWrap(fmt.Errorf("could not register types: %w", err)))
	}

	queued := &QueuedIntArray{}

	queuedQuery := batch.Queue(intArraySQL)
	queuedQuery.Fn = func(br pgx.BatchResults) error {
		rows, err := br.Query()
		if err != nil {
			return queued.runWrapError(err)
		}
		res, err := pgx.CollectRows(rows, pgx.RowTo[[]int32])
		if err != nil {
			return queued.runWrapError(err)
		}

		return queued.runOnResult(res)
	}

	return queued
}
